// AVHRR channels
#define AVHRR_CH1 0
#define AVHRR_CH2 1
#define AVHRR_CH3a 2
#define AVHRR_CH3b 2
#define AVHRR_CH4 3
#define AVHRR_CH5 4

// APT section lengths
#define APT_SYNC_LENGTH 39
#define APT_SPACE_LENGTH 47
#define APT_VIDEO_LENGTH 909
#define APT_TELEM_LENGTH 45

// APT section offsets
#define APT_SYNCA 0
#define APT_SPACEA (APT_SYNCA+APT_SYNC_LENGTH)
#define APT_VIDEOA (APT_SPACEA+APT_SPACE_LENGTH)
#define APT_TELEMA (APT_VIDEOA+APT_VIDEO_LENGTH)
#define APT_SYNCB (APT_TELEMA+APT_TELEM_LENGTH)
#define APT_SPACEB (APT_SYNCB+APT_SYNC_LENGTH)
#define APT_VIDEOB (APT_SPACEB+APT_SPACE_LENGTH)
#define APT_TELEMB (APT_VIDEOB+APT_VIDEO_LENGTH)
#define APT_FRAMESIZE (APT_TELEMB+APT_TELEM_LENGTH)

#define HRPT_BLOCK_SIZE 15872